on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: build
jobs:
    py-check:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { os: ubuntu-latest, py: "3.9" }
                    - { os: ubuntu-latest, py: "3.10" }

        env:
            SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
        steps:
            - name: CHECKOUT CODE
              uses: actions/checkout@v2
            - name: SETUP PYTHON
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.config.py }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --user --no-cache-dir Cython
                  pip install --user -r requirements.txt
                  pip install --user -r requirements_dev.txt
                  pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
                  pip install kaggle
            - name: Add project root to PYTHONPATH
              run: echo "PYTHONPATH=${PYTHONPATH}$(pwd)" >> $GITHUB_ENV
            - name: PKG-TEST
              run: |
                  pytest tests/test_write_json.py
                  kaggle datasets download -d headwater/Camels -p /home/runner/.hydrodataset/cache/camels/camels_us/
                  unzip /home/runner/.hydrodataset/cache/camels/camels_us/Camels.zip
                  pytest tests/test_data_cache.py
                  pytest tests/test_train_camels_lstm.py
                  pytest tests/test_evaluate_model.py
